# backend/services/query_generator.py

import json
import re
from datetime import datetime

from services.chroma_client import ChromaClient
from services.langchain_tools import lookup_region
from typing import Any, Dict, List, Optional
from langchain.agents import create_agent
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from config import settings

class QueryGenerationError(Exception):
    pass

class QueryGenerator:
    def __init__(self, chroma_client: ChromaClient) -> None:
        # LLM setup
        self.llm = ChatOpenAI(
            openai_api_base=settings.llm_base_url,
            openai_api_key=settings.llm_api_key,
            model_name=settings.llm_model_name,
            temperature=0,
        )
        self.chroma_client = chroma_client
        # Tools setup
        #self.tools = [lookup_region]
        

        # Prompt setup
        self.prompt ="""
You are an OSINT assistant that converts user questions into valid Elasticsearch JSON queries for gdelt data.

Rules:
1. Return ONLY valid JSON object. No prose, no markdown, no code fences, no metadata.
2. Use only fields that appear in the schema context, for all dates, use V21Date.
3. Do not invent field names.
4. For "top N", "most common", or ranking questions, use a terms aggregation and set top-level "size": 0.
5. Prefer keyword fields or keyword subfields for exact filters, sorting, and terms aggregations.
6. If no specific time range is provided, by default use a 1 year timeframe.
7. Keep the query safe and read-only. Never use scripts.
8. Use concise, production-sensible Elasticsearch queries.

"""

        # Agent setup
        self.agent = create_agent(
            model=self.llm,
            system_prompt=self.prompt
        )

    def _parse_json(self, text: str) -> Dict[str, Any]:
        if not text:
            raise QueryGenerationError("Empty LLM output.")
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
        cleaned = text.strip().replace("```json", "").replace("```", "").strip()
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError:
            match = re.search(r"\{.*\}", cleaned, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group(0))
                except json.JSONDecodeError as e:
                    raise QueryGenerationError(f"Invalid JSON: {e}")
            raise QueryGenerationError("LLM did not return valid JSON.")

    def generate(self, question: str, history: Optional[List[Dict]] = None) -> Dict[str, Any]:
        docs = self.chroma_client.similarity_search(question, k=6)
        schema_context = "\n".join(d.page_content for d in docs)
        messages = []
        if history:
            for item in history:
                if isinstance(item, dict):
                    role = item.get("role") or "user"
                    content = item.get("content") or ""
                else:
                    # It's a Pydantic object (HistoryItem)
                    role = getattr(item, "role", "user") or "user"
                    content = getattr(item, "content", "") or ""
                messages.append({"role": role, "content": content})

        enriched_question = f"""
            Current datetime: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

            Schema context:
            {schema_context}

            User question:
            {question}
            """
        messages.append({"role": "user", "content": enriched_question})
        print(enriched_question)
        response = self.agent.invoke({
            "messages": messages
        }
        )
            
        final_message_content = response["messages"][-1].content
        
        if not final_message_content:
            raise QueryGenerationError("No query generated by agent.")
        
        return self._parse_json(final_message_content)